// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"awesomeProject1/internal/api"
	"awesomeProject1/internal/pkg/zapx"
	"awesomeProject1/internal/repository"
	"awesomeProject1/internal/service"
	"awesomeProject1/ioc"
	"github.com/gin-gonic/gin"
)

// Injectors from wire.go:

func InitApiServer() *gin.Engine {
	zapLogger := ioc.InitZapLogger()
	loggerv1 := logger.NewZapLogger(zapLogger)
	client := ioc.Initkafka()
	syncProducer := ioc.InitSyncProducer(client)
	consumer := ioc.InitSyncConsumer(client)
	locateRepository := repository.NewLocateRepository()
	nodeService := service.NewNodeService(loggerv1, syncProducer, consumer, locateRepository)
	apiServerHandler := api.NewApiServerHandler(nodeService, loggerv1)
	engine := InitGinEngine(apiServerHandler)
	return engine
}

// wire.go:

func InitGinEngine(ApiHandler *api.ApiServerHandler) *gin.Engine {
	server := gin.Default()
	ApiHandler.RegisterApiServerRoute(server)
	return server
}
